# Form implementation generated from reading ui file '.\windows\editexamdialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_exam_dialog(object):
    def setupUi(self, edit_exam_dialog):
        edit_exam_dialog.setObjectName("edit_exam_dialog")
        edit_exam_dialog.resize(271, 330)
        self.label = QtWidgets.QLabel(parent=edit_exam_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.name_input = QtWidgets.QLineEdit(parent=edit_exam_dialog)
        self.name_input.setGeometry(QtCore.QRect(20, 40, 231, 20))
        self.name_input.setObjectName("name_input")
        self.add_task_input = QtWidgets.QLineEdit(parent=edit_exam_dialog)
        self.add_task_input.setGeometry(QtCore.QRect(20, 150, 141, 20))
        self.add_task_input.setObjectName("add_task_input")
        self.add_task_button = QtWidgets.QPushButton(parent=edit_exam_dialog)
        self.add_task_button.setGeometry(QtCore.QRect(170, 150, 81, 23))
        self.add_task_button.setObjectName("add_task_button")
        self.tasks_textbox = QtWidgets.QPlainTextEdit(parent=edit_exam_dialog)
        self.tasks_textbox.setGeometry(QtCore.QRect(20, 180, 231, 111))
        self.tasks_textbox.setReadOnly(False)
        self.tasks_textbox.setObjectName("tasks_textbox")
        self.save_button = QtWidgets.QPushButton(parent=edit_exam_dialog)
        self.save_button.setGeometry(QtCore.QRect(20, 300, 111, 23))
        self.save_button.setObjectName("save_button")
        self.exit_button = QtWidgets.QPushButton(parent=edit_exam_dialog)
        self.exit_button.setGeometry(QtCore.QRect(140, 300, 111, 23))
        self.exit_button.setObjectName("exit_button")
        self.notes_textbox = QtWidgets.QPlainTextEdit(parent=edit_exam_dialog)
        self.notes_textbox.setGeometry(QtCore.QRect(20, 70, 231, 71))
        self.notes_textbox.setObjectName("notes_textbox")

        self.retranslateUi(edit_exam_dialog)
        self.exit_button.clicked.connect(edit_exam_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(edit_exam_dialog)

    def retranslateUi(self, edit_exam_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_exam_dialog.setWindowTitle(_translate("edit_exam_dialog", "Klausur bearbeiten/erstellen"))
        self.label.setText(_translate("edit_exam_dialog", "Klausur bearbeiten/erstellen"))
        self.name_input.setPlaceholderText(_translate("edit_exam_dialog", "Name"))
        self.add_task_input.setPlaceholderText(_translate("edit_exam_dialog", "Add Task (Aufgabe:Punkte)"))
        self.add_task_button.setText(_translate("edit_exam_dialog", "Add"))
        self.save_button.setText(_translate("edit_exam_dialog", "Speichern"))
        self.exit_button.setText(_translate("edit_exam_dialog", "Abbrechen"))
        self.notes_textbox.setPlaceholderText(_translate("edit_exam_dialog", "Notes"))
