# Form implementation generated from reading ui file 'editcoursedialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_course_dialog(object):
    def setupUi(self, edit_course_dialog):
        edit_course_dialog.setObjectName("edit_course_dialog")
        edit_course_dialog.resize(259, 260)
        edit_course_dialog.setStyleSheet("background-color: rgb(206, 211, 196);")
        self.label = QtWidgets.QLabel(parent=edit_course_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.name_input = QtWidgets.QLineEdit(parent=edit_course_dialog)
        self.name_input.setGeometry(QtCore.QRect(20, 40, 231, 20))
        self.name_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.name_input.setObjectName("name_input")
        self.sek_input = QtWidgets.QComboBox(parent=edit_course_dialog)
        self.sek_input.setGeometry(QtCore.QRect(20, 70, 231, 22))
        self.sek_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.sek_input.setEditable(False)
        self.sek_input.setObjectName("sek_input")
        self.sek_input.addItem("")
        self.sek_input.addItem("")
        self.add_student_input = QtWidgets.QLineEdit(parent=edit_course_dialog)
        self.add_student_input.setGeometry(QtCore.QRect(20, 100, 141, 20))
        self.add_student_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.add_student_input.setObjectName("add_student_input")
        self.add_student_button = QtWidgets.QPushButton(parent=edit_course_dialog)
        self.add_student_button.setGeometry(QtCore.QRect(170, 100, 81, 23))
        self.add_student_button.setStyleSheet("background-color: rgb(216, 204, 231);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius:  10px;\n"
"border-color: black;\n"
"border-color: gray;\n"
"font: 14px;")
        self.add_student_button.setObjectName("add_student_button")
        self.students_textbox = QtWidgets.QPlainTextEdit(parent=edit_course_dialog)
        self.students_textbox.setGeometry(QtCore.QRect(20, 130, 231, 151))
        self.students_textbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.students_textbox.setReadOnly(False)
        self.students_textbox.setObjectName("students_textbox")
        self.save_button = QtWidgets.QPushButton(parent=edit_course_dialog)
        self.save_button.setGeometry(QtCore.QRect(20, 290, 111, 23))
        self.save_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;\n"
"")
        self.save_button.setObjectName("save_button")
        self.exit_button = QtWidgets.QPushButton(parent=edit_course_dialog)
        self.exit_button.setGeometry(QtCore.QRect(140, 290, 111, 23))
        self.exit_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(edit_course_dialog)
        self.sek_input.setCurrentIndex(0)
        self.exit_button.clicked.connect(edit_course_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(edit_course_dialog)

    def retranslateUi(self, edit_course_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_course_dialog.setWindowTitle(_translate("edit_course_dialog", "Kurs bearbeiten/erstellen"))
        self.label.setText(_translate("edit_course_dialog", "<html><head/><body><p><span style=\" color:#000000;\">Kurs bearbeiten/erstellen</span></p></body></html>"))
        self.name_input.setPlaceholderText(_translate("edit_course_dialog", "Name"))
        self.sek_input.setCurrentText(_translate("edit_course_dialog", "Sekundarstuffe I"))
        self.sek_input.setItemText(0, _translate("edit_course_dialog", "Sekundarstuffe I"))
        self.sek_input.setItemText(1, _translate("edit_course_dialog", "Sekundarstuffe II"))
        self.add_student_input.setPlaceholderText(_translate("edit_course_dialog", "Add Student Name"))
        self.add_student_button.setText(_translate("edit_course_dialog", "Add"))
        self.save_button.setText(_translate("edit_course_dialog", "Speichern"))
        self.exit_button.setText(_translate("edit_course_dialog", "Abbrechen"))
