# Form implementation generated from reading ui file 'newexamdialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 492)
        Dialog.setStyleSheet("background-color: rgb(206, 211, 196);")
        self.confirm_parameters_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.confirm_parameters_pushButton.setGeometry(QtCore.QRect(60, 170, 201, 24))
        self.confirm_parameters_pushButton.setStyleSheet("background-color: rgb(216, 204, 231);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius:  10px;\n"
"border-color: black;\n"
"border-color: gray;\n"
"font: 14px;")
        self.confirm_parameters_pushButton.setObjectName("confirm_parameters_pushButton")
        self.tasks_tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tasks_tableWidget.setGeometry(QtCore.QRect(10, 210, 311, 241))
        self.tasks_tableWidget.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.tasks_tableWidget.setObjectName("tasks_tableWidget")
        self.tasks_tableWidget.setColumnCount(0)
        self.tasks_tableWidget.setRowCount(0)
        self.name_textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.name_textEdit.setGeometry(QtCore.QRect(50, 50, 261, 21))
        self.name_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;\n"
"")
        self.name_textEdit.setObjectName("name_textEdit")
        self.notes_textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.notes_textEdit.setGeometry(QtCore.QRect(60, 80, 251, 41))
        self.notes_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.notes_textEdit.setObjectName("notes_textEdit")
        self.notes_label = QtWidgets.QLabel(parent=Dialog)
        self.notes_label.setGeometry(QtCore.QRect(10, 80, 49, 16))
        self.notes_label.setObjectName("notes_label")
        self.name_label = QtWidgets.QLabel(parent=Dialog)
        self.name_label.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.name_label.setObjectName("name_label")
        self.header_label = QtWidgets.QLabel(parent=Dialog)
        self.header_label.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.header_label.setObjectName("header_label")
        self.tasks_textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.tasks_textEdit.setGeometry(QtCore.QRect(110, 130, 201, 21))
        self.tasks_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;")
        self.tasks_textEdit.setObjectName("tasks_textEdit")
        self.tasks_label = QtWidgets.QLabel(parent=Dialog)
        self.tasks_label.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.tasks_label.setObjectName("tasks_label")
        self.cancel_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_pushButton.setGeometry(QtCore.QRect(140, 460, 81, 24))
        self.cancel_pushButton.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.confirm_tasks_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.confirm_tasks_pushButton.setGeometry(QtCore.QRect(234, 460, 91, 24))
        self.confirm_tasks_pushButton.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.confirm_tasks_pushButton.setObjectName("confirm_tasks_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confirm_parameters_pushButton.setText(_translate("Dialog", "Bestätigen"))
        self.notes_label.setText(_translate("Dialog", "Notizen:"))
        self.name_label.setText(_translate("Dialog", "Name:"))
        self.header_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:696;\">Klausur erstellen</span></p></body></html>"))
        self.tasks_label.setText(_translate("Dialog", "Anzahl Aufgaben:"))
        self.cancel_pushButton.setText(_translate("Dialog", "Abbrechen"))
        self.confirm_tasks_pushButton.setText(_translate("Dialog", "Bestätigen"))
