# Form implementation generated from reading ui file '.\windows\printdialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_print_dialog(object):
    def setupUi(self, print_dialog):
        print_dialog.setObjectName("print_dialog")
        print_dialog.resize(400, 282)
        self.student_list = QtWidgets.QListWidget(parent=print_dialog)
        self.student_list.setGeometry(QtCore.QRect(10, 10, 381, 201))
        self.student_list.setObjectName("student_list")
        self.selectall_button = QtWidgets.QPushButton(parent=print_dialog)
        self.selectall_button.setGeometry(QtCore.QRect(10, 220, 381, 23))
        self.selectall_button.setObjectName("selectall_button")
        self.printoverview_button = QtWidgets.QPushButton(parent=print_dialog)
        self.printoverview_button.setGeometry(QtCore.QRect(10, 250, 120, 23))
        self.printoverview_button.setObjectName("printoverview_button")
        self.exit_button = QtWidgets.QPushButton(parent=print_dialog)
        self.exit_button.setGeometry(QtCore.QRect(270, 250, 120, 23))
        self.exit_button.setObjectName("exit_button")
        self.printstudent_button = QtWidgets.QPushButton(parent=print_dialog)
        self.printstudent_button.setGeometry(QtCore.QRect(140, 250, 120, 23))
        self.printstudent_button.setObjectName("printstudent_button")
        self.resultname_label = QtWidgets.QLabel(parent=print_dialog)
        self.resultname_label.setEnabled(True)
        self.resultname_label.setGeometry(QtCore.QRect(200, 100, 47, 13))
        self.resultname_label.setText("")
        self.resultname_label.setObjectName("resultname_label")
        self.resultname_label.raise_()
        self.student_list.raise_()
        self.selectall_button.raise_()
        self.printoverview_button.raise_()
        self.exit_button.raise_()
        self.printstudent_button.raise_()

        self.retranslateUi(print_dialog)
        self.exit_button.clicked.connect(print_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(print_dialog)

    def retranslateUi(self, print_dialog):
        _translate = QtCore.QCoreApplication.translate
        print_dialog.setWindowTitle(_translate("print_dialog", "Dialog"))
        self.selectall_button.setText(_translate("print_dialog", "Alle auswählen"))
        self.printoverview_button.setText(_translate("print_dialog", "Auswertung Drucken"))
        self.exit_button.setText(_translate("print_dialog", "Abbrechen"))
        self.printstudent_button.setText(_translate("print_dialog", "Schüler Drucken"))
