# Form implementation generated from reading ui file '.\windows\readresultdialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_read_result_dialog(object):
    def setupUi(self, read_result_dialog):
        read_result_dialog.setObjectName("read_result_dialog")
        read_result_dialog.resize(489, 238)
        read_result_dialog.setStyleSheet("background-color: rgb(206, 211, 196);")
        self.select_course_box = QtWidgets.QComboBox(parent=read_result_dialog)
        self.select_course_box.setGeometry(QtCore.QRect(10, 70, 471, 22))
        self.select_course_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;\n"
"color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(151, 145, 174);")
        self.select_course_box.setObjectName("select_course_box")
        self.file_edit = QtWidgets.QLineEdit(parent=read_result_dialog)
        self.file_edit.setGeometry(QtCore.QRect(10, 100, 471, 21))
        self.file_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;\n"
"color: rgb(0, 0, 0);")
        self.file_edit.setObjectName("file_edit")
        self.select_exam_box = QtWidgets.QComboBox(parent=read_result_dialog)
        self.select_exam_box.setGeometry(QtCore.QRect(10, 40, 471, 22))
        self.select_exam_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;\n"
"color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(151, 145, 174);")
        self.select_exam_box.setObjectName("select_exam_box")
        self.label = QtWidgets.QLabel(parent=read_result_dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.read_file_button = QtWidgets.QPushButton(parent=read_result_dialog)
        self.read_file_button.setGeometry(QtCore.QRect(10, 130, 471, 24))
        self.read_file_button.setStyleSheet("background-color: rgb(216, 204, 231);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius:  10px;\n"
"border-color: black;\n"
"border-color: gray;\n"
"font: 14px;")
        self.read_file_button.setObjectName("read_file_button")
        self.exit_button = QtWidgets.QPushButton(parent=read_result_dialog)
        self.exit_button.setGeometry(QtCore.QRect(250, 180, 231, 24))
        self.exit_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.exit_button.setObjectName("exit_button")
        self.save_button = QtWidgets.QPushButton(parent=read_result_dialog)
        self.save_button.setGeometry(QtCore.QRect(10, 180, 231, 24))
        self.save_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.save_button.setObjectName("save_button")
        self.print_button = QtWidgets.QPushButton(parent=read_result_dialog)
        self.print_button.setGeometry(QtCore.QRect(10, 210, 231, 24))
        self.print_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.print_button.setObjectName("print_button")

        self.retranslateUi(read_result_dialog)
        QtCore.QMetaObject.connectSlotsByName(read_result_dialog)

    def retranslateUi(self, read_result_dialog):
        _translate = QtCore.QCoreApplication.translate
        read_result_dialog.setWindowTitle(_translate("read_result_dialog", "Ergebniss einlesen"))
        self.file_edit.setPlaceholderText(_translate("read_result_dialog", "Dateiname"))
        self.label.setText(_translate("read_result_dialog", "Ergebnisse einlesen"))
        self.read_file_button.setText(_translate("read_result_dialog", "Bewertung Einlesen"))
        self.exit_button.setText(_translate("read_result_dialog", "Abbrechen"))
        self.save_button.setText(_translate("read_result_dialog", "Speichern"))
        self.print_button.setText(_translate("read_result_dialog", "Drucken"))
