# Form implementation generated from reading ui file '.\windows\viewresultdialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_view_result_dialog(object):
    def setupUi(self, view_result_dialog):
        view_result_dialog.setObjectName("view_result_dialog")
        view_result_dialog.resize(322, 71)
        self.select_result_box = QtWidgets.QComboBox(parent=view_result_dialog)
        self.select_result_box.setGeometry(QtCore.QRect(10, 10, 301, 22))
        self.select_result_box.setObjectName("select_result_box")
        self.view_button = QtWidgets.QPushButton(parent=view_result_dialog)
        self.view_button.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.view_button.setObjectName("view_button")
        self.exit_button = QtWidgets.QPushButton(parent=view_result_dialog)
        self.exit_button.setGeometry(QtCore.QRect(170, 40, 141, 23))
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(view_result_dialog)
        self.exit_button.clicked.connect(view_result_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(view_result_dialog)

    def retranslateUi(self, view_result_dialog):
        _translate = QtCore.QCoreApplication.translate
        view_result_dialog.setWindowTitle(_translate("view_result_dialog", "Ergebnisse ansehen"))
        self.view_button.setText(_translate("view_result_dialog", "Anzeigen"))
        self.exit_button.setText(_translate("view_result_dialog", "Abbrechen"))
