# Form implementation generated from reading ui file 'windows/viewdialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_view_dialog(object):
    def setupUi(self, view_dialog):
        view_dialog.setObjectName("view_dialog")
        view_dialog.resize(322, 71)
        view_dialog.setStyleSheet("background-color: rgb(206, 211, 196);")
        self.select_box = QtWidgets.QComboBox(parent=view_dialog)
        self.select_box.setGeometry(QtCore.QRect(10, 10, 301, 22))
        self.select_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"font: 14px;\n"
"color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(151, 145, 174);")
        self.select_box.setObjectName("select_box")
        self.view_button = QtWidgets.QPushButton(parent=view_dialog)
        self.view_button.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.view_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.view_button.setObjectName("view_button")
        self.exit_button = QtWidgets.QPushButton(parent=view_dialog)
        self.exit_button.setGeometry(QtCore.QRect(170, 40, 141, 23))
        self.exit_button.setStyleSheet("background-color: rgb(127, 169, 112);\n"
"border-style: outset;\n"
"border-radius:  10px;\n"
"border-color: white;\n"
"font: bold 14px;")
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(view_dialog)
        self.exit_button.clicked.connect(view_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(view_dialog)

    def retranslateUi(self, view_dialog):
        _translate = QtCore.QCoreApplication.translate
        view_dialog.setWindowTitle(_translate("view_dialog", "Klausur ansehen"))
        self.view_button.setText(_translate("view_dialog", "Anzeigen"))
        self.exit_button.setText(_translate("view_dialog", "Abbrechen"))
