# Form implementation generated from reading ui file '.\viewcoursedialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_View_Course(object):
    def setupUi(self, view_course_dialog):
        view_course_dialog.setObjectName("view_course_dialog")
        view_course_dialog.resize(322, 330)
        self.select_course_box = QtWidgets.QComboBox(parent=view_course_dialog)
        self.select_course_box.setGeometry(QtCore.QRect(10, 10, 301, 22))
        self.select_course_box.setObjectName("select_course_box")
        self.name_edit = QtWidgets.QLineEdit(parent=view_course_dialog)
        self.name_edit.setGeometry(QtCore.QRect(10, 50, 301, 20))
        self.name_edit.setObjectName("name_edit")
        self.student_name_text = QtWidgets.QPlainTextEdit(parent=view_course_dialog)
        self.student_name_text.setGeometry(QtCore.QRect(10, 110, 301, 181))
        self.student_name_text.setObjectName("student_name_text")
        self.select_sek_box = QtWidgets.QComboBox(parent=view_course_dialog)
        self.select_sek_box.setGeometry(QtCore.QRect(10, 80, 301, 22))
        self.select_sek_box.setObjectName("select_sek_box")
        self.select_sek_box.addItem("")
        self.select_sek_box.addItem("")
        self.save_button = QtWidgets.QPushButton(parent=view_course_dialog)
        self.save_button.setGeometry(QtCore.QRect(10, 300, 141, 23))
        self.save_button.setObjectName("save_button")
        self.exit_button = QtWidgets.QPushButton(parent=view_course_dialog)
        self.exit_button.setGeometry(QtCore.QRect(170, 300, 141, 23))
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(view_course_dialog)
        self.exit_button.clicked.connect(view_course_dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(view_course_dialog)

    def retranslateUi(self, view_course_dialog):
        _translate = QtCore.QCoreApplication.translate
        view_course_dialog.setWindowTitle(_translate("view_course_dialog", "Kurs ansehen"))
        self.select_sek_box.setItemText(0, _translate("view_course_dialog", "Sekundarstuffe I"))
        self.select_sek_box.setItemText(1, _translate("view_course_dialog", "Sekundarstuffe II"))
        self.save_button.setText(_translate("view_course_dialog", "Speichern"))
        self.exit_button.setText(_translate("view_course_dialog", "Abbrechen"))
